### ISSUE TITLE
Review 1 - TODO in the description

### ISSUE THREAD

**Issue by craterTheBox** [Promethaes/CappuccinoEngine#125]
Gameplay
- [x] Fix collision
- [x] Fix level loading
- [x] Put unused assets in the game
- [x] Implement health packs, ammo packs, Sednium (RNG?)
- [ ] Make it so that the guns actually shoot inside the reticule (SHOTGUN PLEASE, IT BOTHERS ME)
- [x] Implement loot chests
- [ ] Use ray casting instead of projectiles for most weapons (except for shotty and grenado)
- [ ] Work on the shop
- [ ] Have an endless mode (player runs into room, enemies become kill, repeat)
- [ ] Fix shooting click hold problem??

Engine
- [ ] Rendering
- [ ] Viewports
- [ ] Mesh loading
- [ ] Textures
- [ ] Text rendering
- [ ] Font manager
- [x] Transform class
- [ ] Shaders from file
- [ ] Lights
- [ ] Game objects
- [ ] FMOD
- [ ] Animation system
- [ ] Math?
- [ ] Collision and Rigid body
- [ ] Ray casting
- [ ] Random class
